<?php

/*
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Modified by madcat34 for the Private Recipe Checker fork, 2026.
 * See CHANGELOG.md and the git history for details.
 */

namespace App\Command;

use App\Vcs\VcsProvider;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(name: 'generate:flex-endpoint', description: 'Generates the json files required by Flex')]
class GenerateFlexEndpointCommand extends Command
{
    /** @param resource $inputStream defaults to real stdin; overridable so tests can inject a fake stream */
    public function __construct(
        private VcsProvider $vcsProvider,
        private $inputStream = \STDIN,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addArgument('repository', InputArgument::REQUIRED, 'The name of the repository (e.g. "acme/recipes")')
            ->addArgument('source_branch', InputArgument::REQUIRED, 'The source branch of recipes')
            ->addArgument('flex_branch', InputArgument::REQUIRED, 'The branch of the target Flex endpoint')
            ->addArgument('output_directory', InputArgument::REQUIRED, 'The directory where generated files should be stored')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $repository = $input->getArgument('repository');
        $sourceBranch = $input->getArgument('source_branch');
        $flexBranch = $input->getArgument('flex_branch');
        $outputDir = $input->getArgument('output_directory');

        $aliases = $recipes = $recipeConflicts = [];

        // stdin usually generated by `git ls-tree HEAD */*/*`

        while (false !== $line = fgets($this->inputStream)) {
            [$tree, $package] = explode("\t", trim($line));
            [,, $tree] = explode(' ', $tree);

            if (!file_exists($package.'/manifest.json')) {
                continue;
            }

            $manifest = json_decode(file_get_contents($package.'/manifest.json'), true);
            $version = substr($package, 1 + strrpos($package, '/'));
            $package = substr($package, 0, -1 - \strlen($version));

            foreach ($manifest['aliases'] ?? [] as $alias) {
                $aliases[$alias] = $package;
                $aliases[str_replace('-', '', $alias)] = $package;
            }

            if ($this->generatePackageJson($package, $version, $manifest, $tree, $outputDir)) {
                $recipes[$package][] = $version;
                usort($recipes[$package], 'strnatcmp');

                if (isset($manifest['conflict'])) {
                    uksort($manifest['conflict'], 'strnatcmp');
                    $recipeConflicts[$package][$version] = $manifest['conflict'];
                    uksort($recipeConflicts[$package], 'strnatcmp');
                }
            }
        }

        ksort($aliases, \SORT_NATURAL);
        ksort($recipes, \SORT_NATURAL);
        ksort($recipeConflicts, \SORT_NATURAL);

        file_put_contents($outputDir.'/index.json', json_encode([
            'aliases' => $aliases,
            'recipes' => $recipes,
            'recipe-conflicts' => $recipeConflicts,
            'branch' => $sourceBranch,
            'is_contrib' => false,
            '_links' => $this->buildLinks($repository, $sourceBranch, $flexBranch),
        ], \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES)."\n");

        return Command::SUCCESS;
    }

    /** @return array<string, string> */
    private function buildLinks(string $repository, string $sourceBranch, string $flexBranch): array
    {
        $repositoryUrl = $this->vcsProvider->getRepositoryUrl($repository);

        return [
            'repository' => $repositoryUrl,
            'origin_template' => sprintf('{package}:{version}@%s:%s', $repositoryUrl, $sourceBranch),
            'recipe_template' => $this->vcsProvider->getRawFileUrl($repository, $flexBranch, '{package_dotted}.{version}.json'),
            'recipe_template_relative' => '{package_dotted}.{version}.json',
            'archived_recipes_template' => $this->vcsProvider->getRawFileUrl($repository, $flexBranch, 'archived/{package_dotted}/{ref}.json'),
            'archived_recipes_template_relative' => 'archived/{package_dotted}/{ref}.json',
        ];
    }

    private function generatePackageJson(string $package, string $version, array $manifest, string $tree, string $outputDir): bool
    {
        unset($manifest['aliases'], $manifest['$schema']);

        if (isset($manifest['add-lines']) && is_array($manifest['add-lines'])) {
            foreach ($manifest['add-lines'] as $i => $config) {
                if (isset($config['content']) && is_array($config['content'])) {
                    $manifest['add-lines'][$i]['content'] = implode("\n", $config['content']);
                }
            }
        }

        $files = [];
        $it = new \RecursiveDirectoryIterator($package.'/'.$version);
        $it->setFlags($it::SKIP_DOTS | $it::FOLLOW_SYMLINKS | $it::UNIX_PATHS);

        foreach (new \RecursiveIteratorIterator($it) as $path => $file) {
            $file = substr($path, 1 + \strlen($package.'/'.$version));
            if (is_dir($path) || 'manifest.json' === $file) {
                continue;
            }
            if ('post-install.txt' === $file) {
                $manifest['post-install-output'] = explode("\n", rtrim(str_replace("\r", '', file_get_contents($path)), "\n"));
                continue;
            }
            if ('Makefile' === $file) {
                $manifest['makefile'] = explode("\n", rtrim(str_replace("\r", '', file_get_contents($path)), "\n"));
                continue;
            }
            $contents = file_get_contents($path);
            $files[$file] = [
                'contents' => preg_match('//u', $contents) ? explode("\n", $contents) : base64_encode($contents),
                'executable' => is_executable($path),
            ];
        }

        if (!$manifest) {
            return false;
        }

        ksort($files, \SORT_NATURAL);

        $contents = json_encode(
            [
                'manifests' => [
                    $package => [
                        'manifest' => $manifest,
                        'files' => $files,
                        'ref' => $tree,
                    ],
                ],
            ],
            \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES
        )."\n";
        file_put_contents(sprintf('%s/%s.%s.json', $outputDir, str_replace('/', '.', $package), $version), $contents);

        // save another version for the archives
        $archivedPath = sprintf('%s/archived/%s/%s.json', $outputDir, str_replace('/', '.', $package), $tree);
        if (!file_exists(\dirname($archivedPath))) {
            mkdir(\dirname($archivedPath), 0777, true);
        }
        file_put_contents($archivedPath, $contents);

        return true;
    }
}
