#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload_runtime.php';

use App\Command\DiffRecipeVersionsCommand;
use App\Command\GenerateArchivedRecipesCommand;
use App\Command\GenerateFlexEndpointCommand;
use App\Command\GenerateRecipesReadmeCommand;
use App\Command\LintManifestsCommand;
use App\Command\LintPackagesCommand;
use App\Command\LintPullRequestCommand;
use App\Command\LintYamlCommand;
use App\Command\ListUnpatchedPackagesCommand;
use Symfony\Component\Console\Application;

return function() {
    $app = new Application();

    $app->addCommand(new DiffRecipeVersionsCommand());
    $app->addCommand(new GenerateFlexEndpointCommand());
    $app->addCommand(new GenerateArchivedRecipesCommand());
    $app->addCommand(new GenerateRecipesReadmeCommand());
    $app->addCommand(new LintManifestsCommand());
    $app->addCommand(new LintPackagesCommand());
    $app->addCommand(new LintPullRequestCommand());
    $app->addCommand(new LintYamlCommand());
    $app->addCommand(new ListUnpatchedPackagesCommand());

    return $app;
};
