#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload_runtime.php';

use App\DiffRecipeVersionsCommand;
use App\GenerateArchivedRecipesCommand;
use App\GenerateFlexEndpointCommand;
use App\GenerateRecipesReadmeCommand;
use App\LintManifestsCommand;
use App\LintPackagesCommand;
use App\LintPullRequestCommand;
use App\LintYamlCommand;
use App\ListUnpatchedPackagesCommand;
use Symfony\Component\Console\Application;

return function() {
    $app = new Application();

    $app->addCommand(new DiffRecipeVersionsCommand());
    $app->addCommand(new GenerateFlexEndpointCommand());
    $app->addCommand(new GenerateArchivedRecipesCommand());
    $app->addCommand(new GenerateRecipesReadmeCommand());
    $app->addCommand(new LintManifestsCommand());
    $app->addCommand(new LintPackagesCommand());
    $app->addCommand(new LintPullRequestCommand());
    $app->addCommand(new LintYamlCommand());
    $app->addCommand(new ListUnpatchedPackagesCommand());

    return $app;
};
