name: Update Flex endpoint

on:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: ./.github/workflows/callable-flex-update.yml
        secrets:
            token: ${{ secrets.VCS_TOKEN }}
